/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * arch-leader
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiKeyDto,
  HTTPError,
  LoginDto,
  SignupDto,
  UserDto,
  ValidationError,
  VerifyDto
} from '.././model';

import { customInstance } from '../../utils/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Api Key
 */
export const getAuthApiKey = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiKeyDto>(
      {url: `/auth/api-key`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthApiKeyQueryKey = () => {
    return [
    `/auth/api-key`
    ] as const;
    }

    
export const getGetAuthApiKeyQueryOptions = <TData = Awaited<ReturnType<typeof getAuthApiKey>>, TError = HTTPError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthApiKeyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthApiKey>>> = ({ signal }) => getAuthApiKey(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthApiKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthApiKey>>>
export type GetAuthApiKeyQueryError = HTTPError


export function useGetAuthApiKey<TData = Awaited<ReturnType<typeof getAuthApiKey>>, TError = HTTPError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthApiKey>>,
          TError,
          Awaited<ReturnType<typeof getAuthApiKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthApiKey<TData = Awaited<ReturnType<typeof getAuthApiKey>>, TError = HTTPError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthApiKey>>,
          TError,
          Awaited<ReturnType<typeof getAuthApiKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthApiKey<TData = Awaited<ReturnType<typeof getAuthApiKey>>, TError = HTTPError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Api Key
 */

export function useGetAuthApiKey<TData = Awaited<ReturnType<typeof getAuthApiKey>>, TError = HTTPError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthApiKeyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Login
 */
export const postAuthLogin = (
    loginDto: LoginDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserDto>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto, signal
    },
      options);
    }
  


export const getPostAuthLoginMutationOptions = <TError = ValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginDto}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = LoginDto
    export type PostAuthLoginMutationError = ValidationError

    /**
 * @summary Login
 */
export const usePostAuthLogin = <TError = ValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: LoginDto},
        TContext
      > => {
      return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
    }
    /**
 * @summary Logout
 */
export const postAuthLogout = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getPostAuthLogoutMutationOptions = <TError = HTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {
          

          return  postAuthLogout(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>
    
    export type PostAuthLogoutMutationError = HTTPError

    /**
 * @summary Logout
 */
export const usePostAuthLogout = <TError = HTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthLogoutMutationOptions(options), queryClient);
    }
    /**
 * @summary Resend Otp
 */
export const patchAuthResendOtp = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/auth/resend-otp`, method: 'PATCH', signal
    },
      options);
    }
  


export const getPatchAuthResendOtpMutationOptions = <TError = HTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAuthResendOtp>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAuthResendOtp>>, TError,void, TContext> => {

const mutationKey = ['patchAuthResendOtp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAuthResendOtp>>, void> = () => {
          

          return  patchAuthResendOtp(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAuthResendOtpMutationResult = NonNullable<Awaited<ReturnType<typeof patchAuthResendOtp>>>
    
    export type PatchAuthResendOtpMutationError = HTTPError

    /**
 * @summary Resend Otp
 */
export const usePatchAuthResendOtp = <TError = HTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAuthResendOtp>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAuthResendOtp>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPatchAuthResendOtpMutationOptions(options), queryClient);
    }
    /**
 * @summary Signup
 */
export const postAuthSignup = (
    signupDto: SignupDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserDto>(
      {url: `/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupDto, signal
    },
      options);
    }
  


export const getPostAuthSignupMutationOptions = <TError = ValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSignup>>, TError,{data: SignupDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthSignup>>, TError,{data: SignupDto}, TContext> => {

const mutationKey = ['postAuthSignup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthSignup>>, {data: SignupDto}> = (props) => {
          const {data} = props ?? {};

          return  postAuthSignup(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthSignupMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthSignup>>>
    export type PostAuthSignupMutationBody = SignupDto
    export type PostAuthSignupMutationError = ValidationError

    /**
 * @summary Signup
 */
export const usePostAuthSignup = <TError = ValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSignup>>, TError,{data: SignupDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthSignup>>,
        TError,
        {data: SignupDto},
        TContext
      > => {
      return useMutation(getPostAuthSignupMutationOptions(options), queryClient);
    }
    /**
 * @summary Verify
 */
export const patchAuthVerify = (
    verifyDto: VerifyDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/auth/verify`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: verifyDto, signal
    },
      options);
    }
  


export const getPatchAuthVerifyMutationOptions = <TError = HTTPError | ValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAuthVerify>>, TError,{data: VerifyDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAuthVerify>>, TError,{data: VerifyDto}, TContext> => {

const mutationKey = ['patchAuthVerify'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAuthVerify>>, {data: VerifyDto}> = (props) => {
          const {data} = props ?? {};

          return  patchAuthVerify(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAuthVerifyMutationResult = NonNullable<Awaited<ReturnType<typeof patchAuthVerify>>>
    export type PatchAuthVerifyMutationBody = VerifyDto
    export type PatchAuthVerifyMutationError = HTTPError | ValidationError

    /**
 * @summary Verify
 */
export const usePatchAuthVerify = <TError = HTTPError | ValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAuthVerify>>, TError,{data: VerifyDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAuthVerify>>,
        TError,
        {data: VerifyDto},
        TContext
      > => {
      return useMutation(getPatchAuthVerifyMutationOptions(options), queryClient);
    }
    