/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * arch-leader
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../utils/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Heartbeat
 */
export const getHeartbeat = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/heartbeat/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetHeartbeatQueryKey = () => {
    return [
    `/heartbeat/`
    ] as const;
    }

    
export const getGetHeartbeatQueryOptions = <TData = Awaited<ReturnType<typeof getHeartbeat>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHeartbeatQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHeartbeat>>> = ({ signal }) => getHeartbeat(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHeartbeatQueryResult = NonNullable<Awaited<ReturnType<typeof getHeartbeat>>>
export type GetHeartbeatQueryError = unknown


export function useGetHeartbeat<TData = Awaited<ReturnType<typeof getHeartbeat>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeartbeat>>,
          TError,
          Awaited<ReturnType<typeof getHeartbeat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHeartbeat<TData = Awaited<ReturnType<typeof getHeartbeat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeartbeat>>,
          TError,
          Awaited<ReturnType<typeof getHeartbeat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHeartbeat<TData = Awaited<ReturnType<typeof getHeartbeat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Heartbeat
 */

export function useGetHeartbeat<TData = Awaited<ReturnType<typeof getHeartbeat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHeartbeatQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




