/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * arch-leader
 * OpenAPI spec version: 0.1.0
 */
import type { GetTimesResDtoUserDto } from './getTimesResDtoUserDto';

export interface GetTimesResDtoTimeDto {
  cache_file: string;
  id: string;
  language: string;
  millis: number;
  output_json: string;
  poster: GetTimesResDtoUserDto;
  timestamp: string;
  trace_file: string;
  validated: boolean;
}
