/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * arch-leader
 * OpenAPI spec version: 0.1.0
 */
import type { GetTimesResDtoTimeDto } from './getTimesResDtoTimeDto';

export interface GetTimesResDto {
  times: GetTimesResDtoTimeDto[];
}
