/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * arch-leader
 * OpenAPI spec version: 0.1.0
 */
import type { HTTPErrorDetail } from './hTTPErrorDetail';

export interface HTTPError {
  detail?: HTTPErrorDetail;
  message?: string;
}
