/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * arch-leader
 * OpenAPI spec version: 0.1.0
 */

export interface RecordTimeReqDto {
  cache_file: string;
  language: string;
  millis: number;
  output_json: string;
  trace_file: string;
}
