/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * arch-leader
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationErrorDetail } from './validationErrorDetail';

export interface ValidationError {
  detail?: ValidationErrorDetail;
  message?: string;
}
