/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * arch-leader
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationErrorDetailLocation } from './validationErrorDetailLocation';

export type ValidationErrorDetail = {
  '<location>'?: ValidationErrorDetailLocation;
};
