/*
 * arch-leader
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyDto {
    #[serde(rename = "api_key")]
    pub api_key: String,
}

impl ApiKeyDto {
    pub fn new(api_key: String) -> ApiKeyDto {
        ApiKeyDto {
            api_key,
        }
    }
}

