/*
 * arch-leader
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTimesResDto {
    #[serde(rename = "times")]
    pub times: Vec<models::GetTimesResDtoTimeDto>,
}

impl GetTimesResDto {
    pub fn new(times: Vec<models::GetTimesResDtoTimeDto>) -> GetTimesResDto {
        GetTimesResDto {
            times,
        }
    }
}

