/*
 * arch-leader
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpError {
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl HttpError {
    pub fn new() -> HttpError {
        HttpError {
            detail: None,
            message: None,
        }
    }
}

