/*
 * arch-leader
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordTimeReqDto {
    #[serde(rename = "cache_file")]
    pub cache_file: String,
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "millis")]
    pub millis: i32,
    #[serde(rename = "output_json")]
    pub output_json: String,
    #[serde(rename = "trace_file")]
    pub trace_file: String,
}

impl RecordTimeReqDto {
    pub fn new(cache_file: String, language: String, millis: i32, output_json: String, trace_file: String) -> RecordTimeReqDto {
        RecordTimeReqDto {
            cache_file,
            language,
            millis,
            output_json,
            trace_file,
        }
    }
}

