/*
 * arch-leader
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeDtoUserDto {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: String,
}

impl TimeDtoUserDto {
    pub fn new(email: String, id: String) -> TimeDtoUserDto {
        TimeDtoUserDto {
            email,
            id,
        }
    }
}

