/*
 * arch-leader
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeDto {
    #[serde(rename = "cache_file")]
    pub cache_file: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "millis")]
    pub millis: i32,
    #[serde(rename = "output_json")]
    pub output_json: String,
    #[serde(rename = "poster")]
    pub poster: Box<models::TimeDtoUserDto>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "trace_file")]
    pub trace_file: String,
    #[serde(rename = "validated")]
    pub validated: bool,
}

impl TimeDto {
    pub fn new(cache_file: String, id: String, language: String, millis: i32, output_json: String, poster: models::TimeDtoUserDto, timestamp: String, trace_file: String, validated: bool) -> TimeDto {
        TimeDto {
            cache_file,
            id,
            language,
            millis,
            output_json,
            poster: Box::new(poster),
            timestamp,
            trace_file,
            validated,
        }
    }
}

