/*
 * arch-leader
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationErrorDetail {
    #[serde(rename = "<location>", skip_serializing_if = "Option::is_none")]
    pub less_than_location_greater_than: Option<Box<models::ValidationErrorDetailLocation>>,
}

impl ValidationErrorDetail {
    pub fn new() -> ValidationErrorDetail {
        ValidationErrorDetail {
            less_than_location_greater_than: None,
        }
    }
}

