/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * arch-leader
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetTimesResDto,
  HTTPError,
  RecordTimeReqDto,
  TimeDto,
  ValidationError
} from '.././model';

import { customInstance } from '../../utils/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get All
 */
export const getTime = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTimesResDto>(
      {url: `/time/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTimeQueryKey = () => {
    return [
    `/time/`
    ] as const;
    }

    
export const getGetTimeQueryOptions = <TData = Awaited<ReturnType<typeof getTime>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTime>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTimeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTime>>> = ({ signal }) => getTime(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTime>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTimeQueryResult = NonNullable<Awaited<ReturnType<typeof getTime>>>
export type GetTimeQueryError = unknown


export function useGetTime<TData = Awaited<ReturnType<typeof getTime>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTime>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTime>>,
          TError,
          Awaited<ReturnType<typeof getTime>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTime<TData = Awaited<ReturnType<typeof getTime>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTime>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTime>>,
          TError,
          Awaited<ReturnType<typeof getTime>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTime<TData = Awaited<ReturnType<typeof getTime>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTime>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get All
 */

export function useGetTime<TData = Awaited<ReturnType<typeof getTime>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTime>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTimeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Record
 */
export const postTimeRecord = (
    recordTimeReqDto: RecordTimeReqDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TimeDto>(
      {url: `/time/record`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: recordTimeReqDto, signal
    },
      options);
    }
  


export const getPostTimeRecordMutationOptions = <TError = HTTPError | ValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTimeRecord>>, TError,{data: RecordTimeReqDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postTimeRecord>>, TError,{data: RecordTimeReqDto}, TContext> => {

const mutationKey = ['postTimeRecord'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTimeRecord>>, {data: RecordTimeReqDto}> = (props) => {
          const {data} = props ?? {};

          return  postTimeRecord(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostTimeRecordMutationResult = NonNullable<Awaited<ReturnType<typeof postTimeRecord>>>
    export type PostTimeRecordMutationBody = RecordTimeReqDto
    export type PostTimeRecordMutationError = HTTPError | ValidationError

    /**
 * @summary Record
 */
export const usePostTimeRecord = <TError = HTTPError | ValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTimeRecord>>, TError,{data: RecordTimeReqDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postTimeRecord>>,
        TError,
        {data: RecordTimeReqDto},
        TContext
      > => {
      return useMutation(getPostTimeRecordMutationOptions(options), queryClient);
    }
    